name: My firat workflow
on:
    workflow_dispatch:
        inputs:
            Environments:
                description: Set the environments
                type: choice
                options:
                    - Dev
                    - Staging
                    - Prod
                default: Feature

    pull_request:
        types: [labeled]

env:
    MONGO_URI: ${{vars.MONGO_URL}}
    MONGO_USERNAME: ${{vars.MONGO_UNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_SECRECT}}
        
jobs:
    setup_environments:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        continue-on-error: true
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v7
              with:
                ref: feature_test

            - name: Setup node
              uses: actions/setup-node@v7
              with:
                node_version: 20

            - name: Setup python
              uses: actions/setup-python@v7
              with:
                python-version: '3.13'

            - name: Check node & python version
              run: |
                node -v
                python -v

            - name: Install node packages
              run: npm install

            - name: Run unit test
              run: npm test



